#imports:
#    - { resource: parameters.ini }
#    - { resource: security.yml }

framework:
    secret:          fds88fe80wa8dsf80jewiajf0894j
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: en
        lifetime:       3600
        auto_start:     true

imports:
    cart_bundle:
        resource: @CartBundle/Resources/config/services.yml
    user_bundle:
        resource: @UserBundle/Resources/config/services.yml
    alert_bundle:
        resource: @AlertBundle/Resources/config/config.yml

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
        company_name_long:      "Ajent"
        company_name_short:     "Ajent"
        base_url:               http://ajent.dev5/
        default_email_domain:   ajent.com


## Swiftmailer Configuration
swiftmailer:
    transport:  smtp
    auth_mode:  login
    host:       mail3.ajent.net
    username:   do-not-reply@teamajent.com
    password:   ru9Ruc5enUwape8exacreqafUfrAT4edrey4vudeveFudrukaprAwahewanaphuq

## Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   pdo_mysql
                host:     localhost
                dbname:   ajent
                user:     root
                password: 456123
    orm:
        entity_managers:
            default:
                mappings:
                    MailBundle: { type: annotation, dir: Entity/ }
                    ExternalMailBundle: { type: annotation, dir: Entity/ }
                    UserBundle: { type: annotation, dir: Entity/ }
                    TagCloudBundle: { type: annotation, dir: Entity/ }
                    SearchBundle: { type: annotation, dir: Entity/ }
                    PeopleScannerBundle: { type: annotation, dir: Entity/ }
                    MailRegistrationBundle: { type: annotation, dir: Entity/ }
                    VendorBundle: { type: annotation, dir: Entity/ }
                    AlertBundle: { type: annotation, dir: Entity/ }
                    AppStoreBundle: { type: annotation, dir: Entity/ }
                    CartBundle: { type: annotation, dir: Entity/ }
                    BillingBundle: { type: annotation, dir: Entity/ }
                    PasswordManagerBundle: { type: annotation, dir: Entity/ }

security:
    encoders:
        Oranges\UserBundle\Entity\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            users:
                admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        profiler:
            pattern:  ^/_profiler
            security: false

        wdt:
            pattern:  ^/_wdt
            security: false

        login:
            pattern:  ^/demo/secured/login$
            security: false

        secured_area:
            pattern:    ^/demo/secured/
            form_login:
                check_path: /demo/secured/login_check
                login_path: /demo/secured/login
            logout:
                path:   /demo/secured/logout
                target: /demo/
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        #- { path: /login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
